=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/JsonSchemas/schemaTheme.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "theme",
    "description": "theme schema for 4D Write Pro table wizard",
    "definitions": {
        "style": {
            "type": "object",
            "properties": {
                "textAlign": {
                    "type": "integer"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "borderColor": {
                    "type": "string"
                },
                "borderStyle": {
                    "type": "integer"
                },
                "borderWidth": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "font": {
                    "type": "string"
                },
                "fontFamily": {
                    "type": "string"
                },
                "fontSize": {
                  "type": "string"
                },
                "padding": {
                    "type": "string"
                }
            }
        }
    },
    "type": "object",
      "properties": {
        "default": {
          "description": "Object containing the default style applicable to all rows.",
          "$ref": "#/definitions/style"
        },
        "table": {
          "description": "Object containing the style definition applicable to the table.",
          "$ref": "#/definitions/style"
        },
        "rows": {
          "description": "Object containing the style definition applicable to all rows.",
          "$ref": "#/definitions/style"
        },
        "cells": {
          "description": "Object containing the style definition applicable to all cells.",
          "$ref": "#/definitions/style"
        },
        "header1": {
          "description": "Object containing the style definition applicable to the first header row.",
          "$ref": "#/definitions/style"
        },
        "header2": {
          "description": "Object containing the style definition applicable to the second header row.",
          "$ref": "#/definitions/style"
        },
        "header3": {
          "description": "Object containing the style definition applicable to the third header row.",
          "$ref": "#/definitions/style"
        },
        "header4": {
          "description": "Object containing the style definition applicable to the fourth header row.",
          "$ref": "#/definitions/style"
        },
        "header5": {
          "description": "Object containing the style definition applicable to the fifth header row.",
          "$ref": "#/definitions/style"
        },
        "headers": {
          "description": "Object containing the style definition applicable to the header rows if no specific header row is defined.",
          "$ref": "#/definitions/style"
        },
        "data": {
          "description": "Object containing the style definition applicable to the repeated data row.",
          "$ref": "#/definitions/style"
        },
        "break1": {
          "description": "Object containing the style definition applicable to the first break row.",
          "$ref": "#/definitions/style"
        },
        "break2": {
          "description": "Object containing the style definition applicable to the second break row.",
          "$ref": "#/definitions/style"
        },
        "break3": {
          "description": "Object containing the style definition applicable to the third break row.",
          "$ref": "#/definitions/style"
        },
        "break4": {
          "description": "Object containing the style definition applicable to the fourth break row.",
          "$ref": "#/definitions/style"
        },
        "break5": {
          "description": "Object containing the style definition applicable to the fifth break row.",
          "$ref": "#/definitions/style"
        },
        "breaks": {
          "description": "Object containing the style definition applicable to the break row, if no specific break row is defined.",
          "$ref": "#/definitions/style"
        },
        "bcor": {
          "description": "Object containing the style definition applicable to the bottom carry-over row.",
          "$ref": "#/definitions/style"
        }
    }
}

=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/Themes/CourierNewGreen.json
{
	"default": {
		"backgroundColor": "#F0F0F0",
		"borderColor": "#202020",
		"borderStyle": 0,
		"borderWidth": "0.5pt",
		"font": "Courier New",
		"fontColor": "#101010",
		"fontFamily": "Courier New",
		"fontSize": "9pt",
		"padding": "2pt",
		"alignment": 0
	},
	"table": {
		"borderWidth": "2pt",
		"borderColor": "#274D40",
		"borderStyle": 1
	},
	"header1": {
		"backgroundColor": "#336655",
		"fontColor": "#F2F2F2",
		"fontSize": "14pt",
		"alignment": 2
	},
	"header2": {
		"fontSize": "13pt",
		"fontColor": "#F2F2F2",
		"backgroundColor": "#40806A",
		"alignment": 2
	},
	"header3": {
		"fontSize": "12pt",
		"fontColor": "#F2F2F2",
		"backgroundColor": "#4C987E",
		"alignment": 2
	},
	"data": {
		"fontColor": "#202020",
		"fontSize": "10pt"
	},
	"break1": {
		"fontSize": "14pt",
		"fontColor": "#F2F2F2",
		"backgroundColor": "#336655",
		"alignment": 1
	},
	"break2": {
		"fontSize": "13pt",
		"fontColor": "#F2F2F2",
		"backgroundColor": "#40806A",
		"alignment": 1
	},
	"break3": {
		"fontSize": "12pt",
		"fontColor": "#F2F2F2",
		"backgroundColor": "#4C987E",
		"alignment": 1
	},
	"bcor": {
		"backgroundColor": "#B7E5D6",
		"alignment": 2,
		"fontSize": "10pt"
	}
}

=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/Themes/TahomaGrey.json
{
	"default": {
		"backgroundColor": "#F0F0F0",
		"borderColor": "#202020",
		"borderStyle": 0,
		"borderWidth": "0.5pt",
		"font": "Tahoma",
		"color": "#101010",
		"fontFamily": "Tahoma",
		"fontSize": "9pt",
		"padding": "2pt",
		"textAlign": 0
	},
	"table": {
		"borderWidth": "2pt",
		"borderColor": "#4B4B4B",
		"borderStyle": 1
	},
	"header1": {
		"backgroundColor": "#666666",
		"color": "#F2F2F2",
		"fontSize": "14pt",
		"textAlign": 2
	},
	"header2": {
		"fontSize": "13pt",
		"color": "#F2F2F2",
		"backgroundColor": "#7F7F7F",
		"textAlign": 2
	},
	"header3": {
		"fontSize": "12pt",
		"color": "#F2F2F2",
		"backgroundColor": "#9A9A9A",
		"textAlign": 2
	},
	"data": {
		"color": "#202020",
		"fontSize": "10pt"
	},
	"break1": {
		"fontSize": "14pt",
		"color": "#F2F2F2",
		"backgroundColor": "#666666",
		"textAlign": 1
	},
	"break2": {
		"fontSize": "13pt",
		"color": "#F2F2F2",
		"backgroundColor": "#7F7F7F",
		"textAlign": 1
	},
	"break3": {
		"fontSize": "12pt",
		"color": "#F2F2F2",
		"backgroundColor": "#9A9A9A",
		"textAlign": 1
	},
	"bcor": {
		"backgroundColor": "#CDCDCD",
		"textAlign": 2,
		"fontSize": "10pt"
	}
}

=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/Themes/ArialBlue.json
{
	"default": {
		"backgroundColor": "#F0F0F0",
		"borderColor": "#202020",
		"borderStyle": 0,
		"borderWidth": "0.5pt",
		"font": "Arial",
		"fontColor": "#101010",
		"fontFamily": "Arial",
		"fontSize": "9pt",
		"padding": "2pt",
		"alignment": 0
	},
	"table": {
		"borderWidth": "2pt",
		"borderColor": "#093C83",
		"borderStyle": 1
	},
	"header1": {
		"backgroundColor": "#094090",
		"fontColor": "#F0F0FF",
		"fontSize": "14pt",
		"alignment": 2
	},
	"header2": {
		"fontSize": "13pt",
		"fontColor": "#F0F0FF",
		"backgroundColor": "#3D6399",
		"alignment": 2
	},
	"header3": {
		"fontSize": "12pt",
		"fontColor": "#F0F0FF",
		"backgroundColor": "#4874B2",
		"alignment": 2
	},
	"data": {
		"fontColor": "#202020",
		"fontSize": "10pt"
	},
	"break1": {
		"fontSize": "14pt",
		"fontColor": "#F5F8FF",
		"backgroundColor": "#3E7B9A",
		"alignment": 1
	},
	"break2": {
		"fontSize": "13pt",
		"fontColor": "#F5F8FF",
		"backgroundColor": "#478EB2",
		"alignment": 1
	},
	"break3": {
		"fontSize": "12pt",
		"fontColor": "#F5F8FF",
		"backgroundColor": "#4FA2CB",
		"alignment": 1
	},
	"bcor": {
		"backgroundColor": "#CBE9F9",
		"borderColor": "#ACB0C0",
		"alignment": 2,
		"fontSize": "10pt"
	}
}

=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/Themes/TimesNewRomanGrey.json
{	"default": {		"backgroundColor": "#F0F0F0",		"borderColor": "#202020",		"borderStyle": 0,		"borderWidth": "0.5pt",		"font": "Times New Roman",		"color": "#101010",		"fontFamily": "Times New Roman",		"fontSize": "9pt",		"padding": "2pt",		"alignment": 0	},	"table": {		"borderWidth": "2pt",		"borderColor": "#4B4B4B",		"borderStyle": 1	},	"header1": {		"backgroundColor": "#666666",		"color": "#F2F2F2",		"fontSize": "14pt",		"alignment": 2	},	"header2": {		"fontSize": "13pt",		"color": "#F2F2F2",		"backgroundColor": "#7F7F7F",		"alignment": 2	},	"header3": {		"fontSize": "12pt",		"color": "#F2F2F2",		"backgroundColor": "#9A9A9A",		"alignment": 2	},	"data": {		"color": "#202020",		"fontSize": "10pt"	},	"break1": {		"fontSize": "14pt",		"color": "#F2F2F2",		"backgroundColor": "#666666",		"alignment": 1	},	"break2": {		"fontSize": "13pt",		"color": "#F2F2F2",		"backgroundColor": "#7F7F7F",		"alignment": 1	},	"break3": {		"fontSize": "12pt",		"color": "#F2F2F2",		"backgroundColor": "#9A9A9A",		"alignment": 1	},	"bcor": {		"backgroundColor": "#CDCDCD",		"alignment": 2,		"fontSize": "10pt"	}}

=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/Themes/TimesNewRomanBlue.json
{
	"default": {
		"backgroundColor": "#F0F0F0",
		"borderColor": "#202020",
		"borderStyle": 0,
		"borderWidth": "0.5pt",
		"font": "Times New Roman",
		"color": "#101010",
		"fontFamily": "Times New Roman",
		"fontSize": "9pt",
		"padding": "2pt",
		"textAlign": 0
	},
	"table": {
		"borderWidth": "2pt",
		"borderColor": "#072F80",
		"borderStyle": 1
	},
	"header1": {
		"backgroundColor": "#094090",
		"color": "#F0F0FF",
		"fontSize": "14pt",
		"textAlign": 2
	},
	"header2": {
		"fontSize": "13pt",
		"color": "#F0F0FF",
		"backgroundColor": "#3D6399",
		"textAlign": 2
	},
	"header3": {
		"fontSize": "12pt",
		"color": "#F0F0FF",
		"backgroundColor": "#4874B2",
		"textAlign": 2
	},
	"data": {
		"color": "#202020",
		"fontSize": "10pt"
	},
	"break1": {
		"fontSize": "14pt",
		"color": "#F5F8FF",
		"backgroundColor": "#3E7B9A",
		"textAlign": 1
	},
	"break2": {
		"fontSize": "13pt",
		"color": "#F5F8FF",
		"backgroundColor": "#478EB2",
		"textAlign": 1
	},
	"break3": {
		"fontSize": "12pt",
		"color": "#F5F8FF",
		"backgroundColor": "#4FA2CB",
		"textAlign": 1
	},
	"bcor": {
		"backgroundColor": "#CBE9F9",
		"borderColor": "#ACB0C0",
		"textAlign": 2,
		"fontSize": "10pt"
	}
}

=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/Themes/ArialGreen.json
{
	"default": {
		"backgroundColor": "#F0F0F0",
		"borderColor": "#202020",
		"borderStyle": 1,
		"borderWidth": "0.5pt",
		"font": "Arial",
		"color": "#101010",
		"fontFamily": "Arial",
		"fontSize": "9pt",
		"padding": "2pt",
		"textAlign": 0
	},
	"table": {
		"borderWidth": "2pt",
		"borderColor": "#005810"
	},
	"rows": {
		"borderWidth": "1pt"
	},
	"cells": {
		"borderWidth": "0.2pt"
	},
	"header1": {
		"backgroundColor": "#336655",
		"color": "#F2F2F2",
		"fontSize": "14pt",
		"textAlign": 2
	},
	"header2": {
		"fontSize": "13pt",
		"color": "#F2F2F2",
		"backgroundColor": "#40806A",
		"textAlign": 2
	},
	"header3": {
		"fontSize": "12pt",
		"color": "#F2F2F2",
		"backgroundColor": "#4C987E",
		"textAlign": 2
	},
	"data": {
		"color": "#202020",
		"fontSize": "10pt"
	},
	"break1": {
		"fontSize": "14pt",
		"color": "#F2F2F2",
		"backgroundColor": "#336655",
		"textAlign": 1
	},
	"break2": {
		"fontSize": "13pt",
		"color": "#F2F2F2",
		"backgroundColor": "#40806A",
		"textAlign": 1
	},
	"break3": {
		"fontSize": "12pt",
		"color": "#F2F2F2",
		"backgroundColor": "#4C987E",
		"textAlign": 1
	},
	"bcor": {
		"backgroundColor": "#B7E5D6",
		"textAlign": 2,
		"fontSize": "10pt"
	}
}
