=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/JsonSchemas/schemaTemplate.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "template",
    "description": "template schema for 4D Write Pro table wizard",
    "definitions": {
        "formula": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            },
            "required": [
                "label",
                "source"
            ]
        }
    },
    "type": "object",
      "properties": {
        "tableDataSource": {
          "description": "Formula of table data source",
          "type": "string"
        },
        "columns": {
          "description": "Collection of table columns",
          "type": "array",
          "items": {
              "type": "object",
                "properties": {
                    "check": {
                        "type": "boolean"
                    },
                    "header": {
                        "type": "string"
                    },
                    "source": {
                        "type": "string"
                    }
                },
                "required": [
                  "check",
                  "header",
                  "source"
                ]
          }
        },
        "breaks": {
          "description": "Collection of break objects",
          "type": "array",
          "items": {
              "$ref": "#/definitions/formula"
          }
        },
        "breakFormulas": {
          "description": "Collection of formula objects applicable to break rows",
          "type": "array",
          "items": {
              "$ref": "#/definitions/formula"
          }
        },
        "bcorFormulas": {
          "description": "Collection of formula objects applicable to bottom carry-over rows",
          "type": "array",
          "items": {
              "$ref": "#/definitions/formula"
          }
        },
        "extraFormulas": {
          "description": "Collection of formula objects applicable to extra rows ",
          "type": "array",
          "items": {
              "$ref": "#/definitions/formula"
          }
        }
    },
      "required": [ "tableDataSource", "columns" ]
}

=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/Templates/documents_5.json
{
	"tableDataSource": "ds.Sample.all().orderBy(\"ID asc\")",
	
	"columns": [
		{
			"check": true,
			"header": "ID",
			"source": "This.item.ID"
		},
		{
			"check": true,
			"header": "Title",
			"source": "This.item.title"
		}
	],
	"breaks": [
		{
			"label": "Title",
			"source": "This.item.title"
		}
	],
	"breakFormulas": [
		{
			"label": "Count",
			"source": "This.breakItems.count(); \"###,##0\")"
		}
	],
	"bcorFormulas": [
		{
			"label": "Count",
			"source": "This.tableData.count(); \"###,##0\")"
		}
	],
	"extraFormulas": [
		{
			"label": "Count",
			"source": "This.tableData.count(); \"###,##0\")"
		}
	]
}

=== 4d/4D-WritePro-Interface/Resources/4DWP_Wizard/Templates/documents_3.json
{
	"tableDataSource": "ds.Sample.all().orderBy(\"ID desc\")",
	
	"columns": [
		{
			"check": true,
			"header": "Title",
			"source": "This.item.title"
		},
		{
			"check": true,
			"header": "ID",
			"source": "This.item.ID"
		}

	],
	"breaks": [
		{
			"label": "Title",
			"source": "This.item.title"
		}
	],
	"breakFormulas": [
		{
			"label": "Count",
			"source": "This.breakItems.count(); \"###,##0\")"
		}
	],
	"bcorFormulas": [
		{
			"label": "Count",
			"source": "This.tableData.count(); \"###,##0\")"
		}
	],
	"extraFormulas": [
		{
			"label": "Count",
			"source": "This.tableData.count(); \"###,##0\")"
		}
	]
}
